spring:
  datasource:
    url: jdbc:h2:mem:librarydb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      data-locations: classpath:db/h2/data.sql
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true #this is key for data generation