server:
  servlet:
    context-path: /api
    session:
      tracking-modes: COOKIE
  port: 8080
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB