server:
  servlet:
    context-path: /api
spring:
  #datasource:
    #url: jdbc:h2:mem:librarydb
    #username: sa
    #password: password
    #driver-class-name: org.h2.Driver
  #h2:
   # console:
    #  enabled: true
   #   path: /h2
  #jpa:
  #  show-sql: true
  #  hibernate:
   #   ddl-auto: create-drop
  #  properties:
   #   hibernate.format_sql: true
  #  defer-datasource-initialization: true  #since spring boot 2.5.0 required for initialization
  #sql:
    #init:
      #data-locations: classpath:db/data.sql

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
