server:
  servlet:
    context-path: /api
  port: 8080
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    user:
      name: user
      password: a
