server:
  servlet:
    context-path: /api
  port: 8080
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

book.new-additional-time: 14  #in days
copy.return-time: 30  #in days
security.jwt.validity-time: 30  #in minutes
