spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true  #since spring boot 2.5.0 required for initialization
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 5
server:
  servlet:
    session:
      tracking-modes: COOKIE
  port: 8080
logging:
  file:
    path: /var/logs/library